export const types = {
    LOGIN_START:'LOGIN_START',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',


    REGISTER_START:'REGISTER_START',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILED:'REGISTER_FAILED',

    GET_EJECUTIVO_START:'GET_EJECUTIVO_START',
    GET_EJECUTIVO_SUCCESS:'GET_EJECUTIVO_SUCCESS',
    GET_EJECUTIVO_FAILED:'GET_EJECUTIVO_FAILED',

    POST_EJECUTIVO_START:'POST_EJECUTIVO_START',
    POST_EJECUTIVO_SUCCESS:'POST_EJECUTIVO_SUCCESS',
    POST_EJECUTIVO_FAILED:'POST_EJECUTIVO_FAILED',

    DELETE_EJECUTIVO_START:'DELETE_EJECUTIVO_START',
    DELETE_EJECUTIVO_SUCCESS:'DELETE_EJECUTIVO_SUCCESS',
    DELETE_EJECUTIVO_FAILED:'DELETE_EJECUTIVO_FAILED',

    UPDATE_EJECUTIVO_START:'UPDATE_EJECUTIVO_START',
    UPDATE_EJECUTIVO_SUCCESS:'UPDATE_EJECUTIVO_SUCCESS',
    UPDATE_EJECUTIVO_FAILED:'UPDATE_EJECUTIVO_FAILED',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',
}