export {default as CreateEjecutivo} from './CreateEjecutivo'
export {default as EditEjecutivo} from './EditEjecutivo'
export {default as DeleteEjecutivo} from './DeleteEjecutivo'
export {default as CreateVehicle} from './CreateVehicle'
export {default as DeleteVehicle} from './DeleteVehicle'
export {default as EditVehicle} from './EditVehical'
export {default as CreateProtector} from './CreateProtector'
export {default as EditProtector} from './EditProtector'
export {default as DeleteProtector} from './DeleteProtector'
export {default as CreateVehicleProtect} from './CreateVehicleProtect'
export {default as EditVehicleProtect} from'./EditVechicleProtect'
export {default as DeleteVehicleProtect} from './DeleteVehicleProtect'